# Project information
site_name: Conentdesk.io Dokumentation
site_url: https://docs.contentdesk.io
theme:
  name: material
  logo: assets/logo-contentdesk-blau.svg
  favicon: assets/favicon-180-180.png
  features:
    #- navigation.instant
    #- navigation.instant.progress
    #- navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.expand
    #- navigation.indexes
    #- toc.follow
    #- toc.integrate
    #- navigation.top
    - content.tabs.link
    - content.code.copy
    - content.action.view
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - stylesheets/contentdesk.css
  - https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css
  - https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css
  - https://cdn.datatables.net/responsive/2.5.0/css/responsive.bootstrap5.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.7.0.min.js
  - https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js
  - https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js
  - https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js
  - https://cdn.datatables.net/responsive/2.5.0/js/responsive.bootstrap5.min.js
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/datatables-init.js
  - javascripts/tablesort.js

plugin:
  - search
  - table-reader:
      data_path: "docs/assets"
  - tags:
      enabled: true
      tags: true
      tags_file: tags.md
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: false
      type: datetime
      format: "%d.%m.%Y"


markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.superfences

# Page tree
nav:
  - Home: index.md
#  - Erste Schritte: getting-started.md
  - Projekte: projects.md
  - Konzepte: concepts.md
  - Schema: schema.md
  - Entwicklung: dev/index.md
  - Verbindungen: 
    - connect.md
    - discover.swiss: connect/discover.md
    - Outdooractive: connect/outdooractive.md
#  - API: api/index.md
  - Ã„nderungen: 
    - System: changelog/system.md
    - Schema / Datenmodell: changelog/schema.md